[profile.default]
src = "src"
out = "out"
libs = ["lib"]
broadcast = "broadcast"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Sepolia Testnet Configuration
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/95mOFxmHTgUtRNCMnfJRe"

[etherscan]
sepolia = { key = "3DKHSI3QE8A294QZKHDR2P5M1B1FFAJD1B" }
