[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 1
via_ir = true
evm_version = "paris"

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

[profile.default.zksync]
enable_eravm_extensions = true

gas_reports = ["*"]

[profile.default.metadata]
bytecode_hash = "none"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Sepolia Testnet Configuration
[rpc_endpoints]
sepolia = "INSERT_URL_HERE"
abstractTestnet  = "INSERT_URL_HERE"

[etherscan]
sepolia = { key = "INSERT_KEY_HERE" }
abstractTestnet  = { chain = "11124", url = "https://api-sepolia.abscan.org/api",key = "INSERT_KEY_HERE" }